-- 코드를 입력하세요
SELECT 
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT UI.USER_ID) AS USERS
FROM ONLINE_SALE AS OS
JOIN USER_INFO AS UI
ON OS.USER_ID = UI.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER;