-- 코드를 입력하세요
SELECT CAR.CAR_ID, CAR.CAR_TYPE, 
    ROUND((CAR.DAILY_FEE * (100 - PLAN.DISCOUNT_RATE)/100 * 30), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
ON CAR.CAR_TYPE = PLAN.CAR_TYPE AND PLAN.DURATION_TYPE = '30일 이상'
WHERE CAR.CAR_TYPE IN ('세단', 'SUV')
    AND CAR.CAR_ID NOT IN (
        SELECT DISTINCT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR.CAR_TYPE ASC, CAR.CAR_ID DESC;