-- 코드를 입력하세요
SELECT COUNT(USER_ID) INTO @USER_COUNT FROM USER_INFO WHERE YEAR(JOINED) = 2021;

SELECT 
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT O.USER_ID) / @USER_COUNT, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS O
JOIN (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021) AS U
ON O.USER_ID = U.USER_ID
GROUP BY YEAR, MONTH;