-- 코드를 입력하세요
WITH RECURSIVE GET_HOUR (HOUR) AS
(
    SELECT 0
    UNION ALL
    SELECT HOUR + 1 FROM GET_HOUR WHERE HOUR < 23
)
SELECT GH.HOUR, IFNULL(COUNT, 0) AS COUNT
FROM GET_HOUR AS GH
LEFT JOIN (SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
            FROM ANIMAL_OUTS
            GROUP BY HOUR(DATETIME)) AS OUTS
ON GH.HOUR = OUTS.HOUR;