-- 코드를 입력하세요
SELECT 
    USER.USER_ID, USER.NICKNAME, 
    CONCAT(CITY,' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소,
    CONCAT_WS('-', SUBSTR(USER.TLNO, 1,3), SUBSTR(USER.TLNO, 4,4), SUBSTR(USER.TLNO, 8)) AS 전화번호
FROM USED_GOODS_USER AS USER, USED_GOODS_BOARD AS BOARD
WHERE USER.USER_ID = BOARD.WRITER_ID
GROUP BY USER.USER_ID
HAVING COUNT(*) >= 3
ORDER BY USER.USER_ID DESC;