-- 코드를 입력하세요
SELECT 
    MEMBER_NAME, REVIEW_TEXT, 
    DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS REST
JOIN MEMBER_PROFILE AS MEMBER
ON REST.MEMBER_ID = MEMBER.MEMBER_ID
WHERE MEMBER.MEMBER_ID = (  SELECT MEMBER_ID
                            FROM REST_REVIEW
                            GROUP BY MEMBER_ID
                            ORDER BY COUNT(*) DESC LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT;