-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY,
    SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES AS BS, BOOK AS B, AUTHOR AS A
WHERE BS.BOOK_ID = B.BOOK_ID
    AND B.AUTHOR_ID = A.AUTHOR_ID
    AND BS.SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;