-- 코드를 입력하세요
SELECT 
    HISTORY.CAR_ID,
    IF(RENT.CAR_ID IS NULL, '대여 가능', '대여중') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
LEFT JOIN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
        ) AS RENT
ON HISTORY.CAR_ID = RENT.CAR_ID
GROUP BY HISTORY.CAR_ID
ORDER BY HISTORY.CAR_ID DESC;