-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, PT.PT_NO, APNT.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT AS APNT, DOCTOR AS DR, PATIENT AS PT
WHERE   APNT.MDDR_ID = DR.DR_ID
        AND APNT.PT_NO = PT.PT_NO
        AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
        AND APNT_CNCL_YN = 'N' 
        AND APNT.MCDP_CD = 'CS'
ORDER BY APNT_YMD;