-- 코드를 입력하세요
SELECT CAR.CAR_ID
FROM 
    CAR_RENTAL_COMPANY_CAR AS CAR, 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
WHERE 
    CAR.CAR_ID = HISTORY.CAR_ID 
    AND HISTORY.START_DATE LIKE '2022-10%'
    AND CAR.CAR_TYPE = '세단'
GROUP BY CAR.CAR_ID
ORDER BY CAR.CAR_ID DESC;