-- 코드를 입력하세요
# SELECT COUNT(USER_ID) AS USERS
# FROM USER_INFO
# WHERE ( AGE BETWEEN 20 AND 29 )
#     AND JOINED LIKE '2021%';

SELECT COUNT(USER_ID) AS USERS
FROM USER_INFO 
WHERE DATE_FORMAT(JOINED, '%Y') = '2021'
AND AGE BETWEEN 20 AND 29;